[app]
name = Sweet Juice
package = com.sweetjuice.app
icon=appIcon.png
description = A demonstration app to showcase the capabilities of Sweet Juice.
version = 1.0
versionCode = 1

[build]
# Frontend build command: npm run build or yarn build
frontend_dir = ./frontend/
frontend_build_command = npm install && npm run build
# Build Type: debug or release
type = debug
# Build Architectures: arm64, armv7, x86_64, universal
android_target = arm64
ios_target = arm64

[android]
# Minimum API version
min_api = 21
# Native Compiled Bindings
aar_name = sweetjuice.aar

# APK/AAB Signing Configurations
## Change these values to your own keystore and key information for signing the APK/AAB
keystore = sweetjuice.keystore
key_alias = sweetjuice
key_password = sweetjuice

[ios]
# Minimum iOS version
min_version = 12.0
# Native Compiled Bindings
xframework_name = Sweetjuice.xcframework
